### PR TITLE
Add more configuration options for openid connect

### PR DESCRIPTION
**Pull request by stdweird**
Based on #18

### CODE REVIEW

**Comment by stdweird** [comment]
@theferrit32 This PR contains some fixes, i'll add more refactoring here

**Comment by stdweird** [comment]
@theferrit32 a lot more refactoring, best to retest with this branch
Following remark still valid https://github.com/heliumdatacommons/auth_microservice/pull/18#issuecomment-425473860

**Comment by stdweird** [comment]
@theferrit32 thanks for enabling travis. i'd prefer to fix the undefined token_endpoint in this PR, so if it is only a matter of adding a
```python
token_endpoint = get_provider_config(provider, 'token_endpoint')
```
to the code, i'll do that

**Comment by theferrit32** [comment]
@stdweird I have confirmed login and token querying operations working for basic backends like Globus+Google.

I have a small fix for Auth0 which I can add after merging these changes.

Was there a reason that this encode statement was needed?
https://github.com/heliumdatacommons/auth_microservice/blob/75d1635dc6db9c9fc9a1e5ab79008c11ab543c92/token_service/base_settings.py#L123
It is causing this mismatch when the Authorization header is checked and is str type:
Python 3.6:
```
>>> b'123' == '123'
False
```
Python 2.7:
```
>>> b'123' == '123'
True
```

**Comment by stdweird** [comment]
@theferrit32 not that i know. looks like it was already there before i started to cleanup
https://github.com/heliumdatacommons/auth_microservice/pull/15/files#diff-82b66d9d4456d8e2be38f5cb6eb3e942L122

**Pull request merged**
