### PR TITLE
Add support for python 2.7 and django 1.8

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
@theferrit32 can you enable this repo on travis? (i can only enable travis for repo i have write access to, eg my fork of this repo)

**Comment by stdweird** [comment]
@theferrit32 Follwoing things are not in the PR:
* new initial migration (but that will break any existing installations)
* flake8 fixes
* actual testing, incl the README deployment

**Comment by stdweird** [comment]
@theferrit32 this PR now also includes changes to resolve the flake8 tests. some code was actually modified in those commits.
on of the thing was the lazy load of the models in the redirect_handler; i just moved it for now.

i'm now going to start testing the service on el7, i expect at least another set of commits to replace the `print` statements with proper logging (i'll add settings config to log to console by default, so it will lokk like print).

**Comment by theferrit32** [comment]
@stdweird Just wanted to let you know I am looking at this now.  I'm in the process of redeploying a server and will review these changes as part of that process.

**Comment by stdweird** [comment]
@theferrit32 ok. i managed to start the service with uwsgi on el7, using only rpms (and config files). but i'm not sure it works yet; still need to actually try it out with our irods testbed.
wrt el7, i'll add some docs because there are some minor changes wrt how to make it work.

**Pull request merged**
